### ISSUE TITLE
When updating custom addons, all imported records erased

### ISSUE THREAD

**Issue by dave08** [tfrancoi/odoo_csv_import#2]
I used this tool to import data, but when I run odoo -u addon_name, it suddenly starts erasing everything I imported...?

**Comment by tfrancoi** [comment]
This is a standard behavior of odoo. It's because you use the same module name for the data you import then the module you upgrade. You should alwyas choose a non existing module as prefix for the external ID. When a module is upgraded; It check the external id present in the module and the one in the database. at the end of the upgrade it remove all the external id of the database that are not contains in the module. This allow to remove old view or old data that are not present in the module anymore. But of course when you import data with the same module name it wipe out all your data.
