### ISSUE TITLE
Question: increased load when importing many lines

### ISSUE THREAD

**Issue by pierrecorsini** [tfrancoi/odoo_csv_import#29]
Hi

I am importing 100.000+ lines of records.

The time it takes to import the 10 first lines is 2 seconds.
The time it takes to import the las 10 lines is 5x longer.

Can anyone advice ? Is that normal ? If after finishing, I run on the same database the import, the first 10 records will take 2 seconds again, this does not seems to be a db-insert issue.

**Comment by tfrancoi** [comment]
Hello,
The import tools, split the file and make a rpc call load, the time between batch script side is constant. If the time is inscreasing, it's because the time spend server side is increasing.

"If after finishing, I run on the same database the import, the first 10 records will take 2 seconds again, this does not seems to be a db-insert issue."
The first thing you need to know is that runing the file again on the same database will not insert more record but update the existing record, so that's perfectly normal to have a different behavior the first time and the second time.

Now, as I said, if the time between batch is inscreasing, it's because the server take more time to process each request. 

One explanation could be that you are running the script with more worker then you have on your server.
The other explaination need a performance analysis of the transaction.

To check the python I recommand the tool py-spy and pgbadger to analyse the log of postgresql.
Common explanation are missing index or you are importing a related field that you should not import and of course there is many more explanation.

**Comment by pierrecorsini** [comment]
Thanks
